language: c
dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

jobs:
    include:
    - stage: linux
      os: linux
      compiler: gcc
    - stage: osx
      os: osx
      compiler: clang

script:
    - mkdir build
    - cd build
    - cmake ../solver
    - make
    
